<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Room;
use Doctrine\ORM\EntityRepository;

class RoomRepository extends EntityRepository
{
    /**
     * @return Room[]
     */
    public function findAll()
    {
        return parent::findAll(); // TODO: Change the autogenerated stub
    }
}