AppBundle\Entity\CalendarRoom:
  type: entity
  table: calendar_rooms
  repositoryClass: AppBundle\Repository\CalendarRoomRepository
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    dateAt:
      type: date
    price:
      type: decimal
    inventory:
      type: integer
  manyToOne:
    room:
      targetEntity: Room
      inversedBy: rooms
      joinColumn:
        name: room_id
        referenceColumnName: id