AppBundle\Entity\CalendarRoom:
  properties:
    room:
      - Valid:
    dateAt:
      - Date:
          groups:
            - InventoryIndividual
            - PriceIndividual
    price:
      - GreaterThanOrEqual:
          value: 0
          groups:
            - PriceIndividual
            - CalendarRoom
    inventory:
      - GreaterThanOrEqual:
          value: 0
          groups:
            - InventoryIndividual
            - CalendarRoom
    start_date:
      - Date:
          groups:
            - CalendarRoom
    end_date:
      - Date:
          groups:
            - CalendarRoom