services:
  app.repository.room:
    class: AppBundle\Repository\RoomRepository
    factory:
      - "@doctrine.orm.entity_manager"
      - getRepository
    arguments: [AppBundle\Entity\Room]

  app.repository.calendar_room:
    class: AppBundle\Repository\CalendarRoomRepository
    factory:
      - "@doctrine.orm.entity_manager"
      - getRepository
    arguments: [AppBundle\Entity\CalendarRoom]

  app.service.calendar.builder:
    class: AppBundle\Service\CalendarBuilder
    arguments:
      - "@app.repository.calendar_room"
      - "@app.repository.room"

  app.service.calendar_updater:
    class: AppBundle\Service\CalendarUpdater
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@app.repository.calendar_room"
      - "@app.repository.room"

  app.service.price_updater:
    class: AppBundle\Service\PriceUpdater
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@app.repository.calendar_room"
      - "@app.repository.room"

  app.service.inventory_updater:
      class: AppBundle\Service\InventoryUpdater
      arguments:
        - "@doctrine.orm.entity_manager"
        - "@app.repository.calendar_room"
        - "@app.repository.room"